version: 2.1

jobs:
  run_tests:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium
    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: Create Virtualenv
          command: |
            virtualenv venv
      - run:
          name: Install Dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
      # Step 3: run pylint styling check
      - run:
          name: Run Pylint Check
          command: |
            . venv/bin/activate
            pylint arbitragelab tests --rcfile=.pylintrc -f text
      # Step 4: run coverage check
      - run:
          name: Run Unit Tests and Coverage Check
          command: |
            bash coverage
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  main:
    jobs:
      - run_tests
